Convert module to typescript
bitfocus/companion-module-getontime-ontime pull request #14
Opened 2023-04-04 16:45 UTC by kellhogs

I've converted this module to typescritpp in preparation of the v2 api update

2023-04-04 18:38 UTC, cpvalente commented
This looks good from app side, good work
@josephdadams  or @Julusian  would you guys be available for some sanity check?

Also, is it possible to add collaborator permissions to @kellhogs , he is maintaining the module on its own at this moment

2023-04-10 09:58 UTC, dnmeid requested changes

2023-04-10 09:58 UTC, dnmeid commented on package.json
> +		"@companion-module/base": "^1.2.1",
Not a good idea to get base with ^, you should use the lowest version you really need with ~
With ^1.2.1 you currently get 1.4.0 and that is not compatible with the beta branch of Companion 3.0

2023-04-10 10:02 UTC, kellhogs commented on package.json
> +		"@companion-module/base": "^1.2.1",
good catch that i actually already reverted back to ~1.2.1 for the next pr i have in line. Anyway i will revert it here to.

2023-04-13 16:33 UTC, dnmeid commented
I guess you just did the change in source and then did not run yarn again. So currently yarn.lock still is pointing to base v1.4.
The current beta has now been updated to base 1.4 too, so this won't be a problem any more for users running the very latest beta.
Just tell me if you want it to be merged like this or if you want to sync yarn.lock with package.json before.

2023-04-13 16:57 UTC, kellhogs commented
I've synced the yarn.lock and it qould be great if you could merge here. I think we dont need to create a new release here tho cause i've already finished the update for the V2 API update. Once you have merged i'll try to rule out any merge conflicts that might turn up and the post the next PR. 

Looking out for what you have to say to it

2023-04-30 12:27 UTC, merged