Feat/v2 api
bitfocus/companion-module-getontime-ontime pull request #17
Opened 2023-04-30 13:09 UTC by kellhogs

Add: support for the websocket API of Ontime V2

New Action: Start event's from a dropdown list, wich get's refetched on change of ontime using the new refetch endpoint from Ontime (thanks to @markspolakovs)
New Action: Load event's from a dropdown list, wich get's refetched on change of ontime using the new refetch endpoint from Ontime (thanks to @markspolakovs)
New Action: Start next event

2023-05-19 20:18 UTC, dnmeid requested changes

2023-05-19 20:18 UTC, dnmeid commented on src/index.ts
> +		if (config.version === 'v1') {
What happens if you open an existing configuration after module upgrade? config.version will be undefined.

2023-05-19 20:18 UTC, dnmeid commented on package.json
> +	"version": "3.0.0",
I see that this is a big update, but where is the breaking change? You should handle undefined values for fields not existing in v2.0.2 and then this is v2.1.0

2023-05-19 20:25 UTC, kellhogs commented on src/config.ts
> +				'^(http://www.|https://www.|http://|https://)?[a-z0-9]+([-.]{1}[a-z0-9]+)*.[a-z]{2,5}(:[0-9]{1,5})?(/.*)?|^((http://www.|https://www.|http://|https://)?([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[
do you have a suggestion for a regex that will validate for ip's and url's? or would you want me to remove the regex?

2023-05-19 20:51 UTC, kellhogs commented on src/config.ts
> +				'^(http://www.|https://www.|http://|https://)?[a-z0-9]+([-.]{1}[a-z0-9]+)*.[a-z]{2,5}(:[0-9]{1,5})?(/.*)?|^((http://www.|https://www.|http://|https://)?([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[
ok seems like `Regex.IP && Regex.HOSTNAME` does work, wich would be good for me

2023-05-21 20:38 UTC, dnmeid requested changes

2023-05-21 20:38 UTC, dnmeid commented on src/config.ts
> +			regex: Regex.IP && Regex.HOSTNAME,
Nope, regex wants to have a JS-string like you would write a regex. e.g. '/^hello World[.!\\\\?]$/i' Keep in mind that slashes need to be backslash-escaped and because it is a JS-String a backslash needs to be backslash-escaped as well, leading to double backslashes.

2023-05-21 20:38 UTC, dnmeid commented on src/config.ts
>  			label: 'Retfetch events',
typo

2023-05-21 20:38 UTC, dnmeid commented on src/index.ts
> +
1. it would be better to check `if (config.version !== 'v1' && config.version !== 'v2')`, so you catch all cases which might fail later
2. you check `config.version` and then you set `this.config.version`, later you check against `config.version`. This technically works here because of pass by reference, but it is bad style leading to possible errors and bad readability
3. after detecting an old config and setting to v1, you should also do the same for the other new options (check if proper value is stored and set to default if not)
4. after all you should safe the config if new options had to be set

2023-05-24 16:17 UTC, dnmeid approved these changes

2023-05-24 16:17 UTC, dnmeid commented on src/index.ts
> -		this.config = config
How do you process updated config data when you remove this line from the configUpdated methos? I might be missing something but I think you need it.

2023-06-02 18:21 UTC, kellhogs commented on src/index.ts
> -		this.config = config
you were right @dnmeid i re added the this.config = config to the code

2023-06-02 18:23 UTC, kellhogs commented
@dnmeid would be great if you could merge this and create a release tag for me (since i dont have the rights to). Provided you don't have any other notes.

2023-06-03 10:17 UTC, merged